const mongoose = require('mongoose');


const brandAndModelsSchema = new mongoose.Schema({
    data : {
        type: Object,
    }
})


module.exports = mongoose.model('brandAndModels', brandAndModelsSchema);





// data = { 
//     "Audi" : [
//     '100', 
//     '200', 
//     '50',
//     '60',
//     '80', 
//     '90', 
//     'A1', 
//     'A2', 
//     'A3', 
//     'A4', 
//     'A4 Allroad', 
//     'A5', 
//     'A6', 
//     'A6 Allroad', 
//     'A7', 
//     'A8', 
//     'Cabriolet', 
//     'Coupe', 
//     'E-Tron', 
//     'Q2', 
//     'Q3', 
//     'Q5', 
//     'Q7', 
//     'Q8', 
//     'Quattro', 
//     'R8', 
//     'RSQ8', 
//     'Rs3', 
//     'Rs4', 
//     'Rs5', 
//     'Rs6', 
//     'Rs7 ', 
//     'S1', 
//     'S2', 
//     'S3', 
//     'S4', 
//     'S5', 
//     'S6', 
//     'S7', 
//     'S8', 
//     'SQ5', 
//     'SQ7', 
//     'SQ8', 
//     'Tt', 
//   ],
//   "Alfa Romeo" : [
//     "145",
//     "146",
//     "147",
//     "155",
//     "156",
//     "156 sportwagon",
//     "159",
//     "159 sportwagon",
//     "164",
//     "166",
//     "33",
//     "4C",
//     "75",
//     "76",
//     "8C Competizione",
//     "90",
//     "Alfetta",
//     "Berlina",
//     "Brera",
//     "Crosswagon q4",
//     "Giulia",
//     "Giulietta",
//     "Gt",
//     "Gtv",
//     "MiTo",
//     "Spider",
//     "Sprint",
//     "Stelvio",
//     "Sud",
//   ],
//   "BMW" : [
//     "114",
//     "116",
//     "118",
//     "120",
//     "123",
//     "125",
//     "130",
//     "135",
//     "1500",
//     "1600",
//     "1602",
//     "1800",
//     "2 Active Tourer",
//     "2 Gran Coupe",
//     "2 Gran Tourer",
//     "2000",
//     "2002",
//     "218",
//     "220 d",
//     "225",
//     "228",
//     "230",
//     "235",
//     "240",
//     "2800",
//     "315",
//     "316",
//     "318",
//     "320",
//     "323",
//     "324",
//     "325",
//     "328",
//     "330",
//     "335",
//     "340",
//     "3gt",
//     "420",
//     "428",
//     "430",
//     "435",
//     "440",
//     "5 Gran Turismo",
//     "504",
//     "518",
//     "520",
//     "523",
//     "524",
//     "525",
//     "528",
//     "530",
//     "530E",
//     "535",
//     "540",
//     "545",
//     "550",
//     "628",
//     "630",
//     "633",
//     "635",
//     "640",
//     "645",
//     "650",
//     "700",
//     "721",
//     "723",
//     "725",
//     "728",
//     "730",
//     "732",
//     "733",
//     "735",
//     "740",
//     "745",
//     "750",
//     "760",
//     "840",
//     "850",
//     "Izetta",
//     "M Series",
//     "M Coupe",
//     "M135",
//     "M2",
//     "M3",
//     "M4",
//     "M5",
//     "M6",
//     "M8",
//     "X1",
//     "X2",
//     "X3",
//     "X4",
//     "X5",
//     "X6",
//     "X7",
//     "Z1",
//     "Z3",
//     "Z4",
//     "X8",
//     "i3",
//     "i8",
//   ],
//   "Bentley" : [
//     "Arnage",
//     "Azure",
//     "Bantyaga",
//     "Continental",
//     "Continental gt",
//     "Flying Spur",
//     "GT Converible",
//     "Mulsanne",
//     "T-series",
//   ],
//   "Bugatti" : [
//     "Chiron",
//     "Veyron",
//   ],
//   "Citroen" : [
//     "2cv",
//     "Ax",
//     "Axel",
//     "Berlingo",
//     "Bx",
//     "C-Zero",
//     "C-Crosser",
//     "C-Elysee",
//     "C1",
//     "C15",
//     "C2",
//     "C3",
//     "C3 Aircross",
//     "C3 Picasso",
//     "C3 pluriel",
//     "C4 ",
//     "C4 Aircross",
//     "C4 Cactus",
//     "C4 Picasso",
//     "C5 Cactus",
//     "C5 Aircross",
//     "C6",
//     "C8",
//     "Cx",
//     "DS 3 Crossback",
//     "DS 4 Crossback",
//     "DS 7 Crossback",
//     "DS3",
//     "DS4",
//     "DS5",
//     "DS7",
//     "Ds",
//     "E-Mehari",
//     "Evasion",
//     "Grand C4 Picasso",
//     "Gsa",
//     "Gx",
//     "Ln",
//     "Nemo",
//     "Oltcit",
//     "Saxo",
//     "Spacetourer",
//     "Visa",
//     "Xantia",
//     "Xm",
//     "Xsara",
//     "Xsara picasso",
//     "Zx",
//   ]
//   }
